export * from "./HomeTemplate";
export * from "./sections/Hero";
export * from "./sections/FeaturesSection";
export * from "./sections/TestimonialsSection";
export * from "./sections/SocialProofScreenshots";
export * from "./sections/PostsSection";
export * from "./sections/FaqSection";
export * from "./sections/PricingCta";
export { AboutSection } from "./sections/AboutSection";
export type { AboutSectionProps } from "./sections/AboutSection";
export * from "./data/team";
export * from "./MagicUiSaasTemplate";
