export const PRIMARY_CATEGORIES = [
  "Downloader",
  "Artificial Intelligence",
  "Adult",
  "Course Platforms",
  "Livestream",
  "Creative Assets",
  "Image Hosting",
  "Movies & TV",
  "Social Media",
] as const;

export type CategoryLabel = (typeof PRIMARY_CATEGORIES)[number];

export type CategoryRule = {
  label: CategoryLabel;
  keywords: string[];
};

export const CATEGORY_RULES: CategoryRule[] = [
  {
    label: "Adult",
    keywords: [
      "adult",
      "porn",
      "xxx",
      "xvideos",
      "xhamster",
      "xnxx",
      "stripchat",
      "cam",
      "camsoda",
      "bonga",
      "beeg",
      "spank",
      "erome",
      "erothots",
      "tnaflix",
      "livejasmin",
      "chaturbate",
      "myfreecams",
      "youporn",
      "redtube",
      "eporner",
      "redgifs",
      "soundgasm",
    ],
  },
  {
    label: "Course Platforms",
    keywords: [
      "course",
      "udemy",
      "skillshare",
      "teachable",
      "academy",
      "learn",
      "learning",
      "education",
      "university",
      "khan",
      "thinkific",
      "kajabi",
      "learndash",
      "moodle",
      "whop",
      "skool",
      "communities",
      "podia",
    ],
  },
  {
    label: "Livestream",
    keywords: [
      "livestream",
      "live stream",
      "stream",
      "twitch",
      "kick",
      "m3u8",
      "live",
      "broadcast",
      "webcast",
    ],
  },
  {
    label: "Creative Assets",
    keywords: [
      "stock",
      "vector",
      "graphic",
      "design",
      "creative",
      "storyblocks",
      "stocksy",
      "stockvault",
      "dreamstime",
      "123rf",
      "vectorstock",
      "freepik",
      "pixabay",
      "unsplash",
      "pexels",
      "rawpixel",
      "depositphotos",
      "shutterstock",
      "adobe",
      "canva",
      "giphy",
      "deviantart",
      "creative market",
    ],
  },
  {
    label: "Image Hosting",
    keywords: [
      "image",
      "photo",
      "gallery",
      "pixabay",
      "pexels",
      "unsplash",
      "deviantart",
      "flickr",
      "giphy",
      "terabox",
      "vectorstock",
      "image hosting",
      "thumbnail",
    ],
  },
  {
    label: "Movies & TV",
    keywords: [
      "movie",
      "movies",
      "film",
      "tv",
      "cinema",
      "123movies",
      "netflix",
      "hulu",
      "tubi",
      "prime",
      "amazon video",
      "vod",
    ],
  },
  {
    label: "Social Media",
    keywords: [
      "social",
      "facebook",
      "instagram",
      "tiktok",
      "youtube",
      "twitter",
      "snapchat",
      "vk",
      "reddit",
      "onlyfans",
      "pinterest",
      "telegram",
      "patreon",
      "circle",
      "clientclub",
      "gokollab",
      "soundcloud",
    ],
  },
];
