#!/usr/bin/env sh

set -e

echo "########################################"
echo "→ Running lints..."
echo "########################################"
pnpm lint

echo "########################################"
echo "→ Running typechecks..."
echo "########################################"
pnpm typecheck

echo "########################################"
echo "→ Running unit tests..."
echo "########################################"
pnpm test:unit

echo "########################################"
echo "→ Building @apps/store"
echo "########################################"
NEXT_TELEMETRY_DISABLED=1 pnpm --filter @apps/store build

echo "✓ Pre-push checks passed"
